# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fca944bc8886be44f6e1a61cbd25aed6"
name = "account-billing"
application_url = "https://account-billing.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_app_proxy"

[webhooks]
api_version = "2026-10"

[auth]
redirect_urls = [
  "https://account-billing.onrender.com/api/auth",
  "https://account-billing.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://account-billing.onrender.com/api/proxy"
subpath = "account-billing"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
